---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/modelServingSupport: '["single"]'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  labels:
    opendatahub.io/dashboard: "true"
  name: rplumber
  namespace: redhat-ods-applications
objects:
- apiVersion: serving.kserve.io/v1alpha1
  kind: ServingRuntime
  labels:
    opendatahub.io/dashboard: "true"
  metadata:
    annotations:
      #opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
      openshift.io/display-name: RPlumber
    name: rplumber
  spec:
    containers:
    - image: rplumber
      name: kserve-container
      ports:
      - containerPort: 8000
        protocol: TCP
    multiModel: false
    supportedModelFormats:
    - autoSelect: true
      name: rds
